project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

website:
  title: "S&P 500 Volatility Clusters"
  page-footer: 
    left: Created by Jianyuan(Andy) Hu, 2024 
    right: |
     This website was built with <a href="https://quarto.org/">Quarto</a>.

  repo-url: https://github.com/jy-andy-hu/sp500_vol_regime
  repo-branch: main
  repo-actions: issue

  sidebar:
    style: "floating"
    search: true
    background: "none"
    tools:
    - icon: linkedin
      href: http://linkedin.com/in/andyhu1
    - icon: github
      href: https://github.com/jy-andy-hu

format: 
    html:
        theme: cerulean
        highlight-style: arrow
        page-layout: full
        toc: true
        toc-location: left
        toc-depth: 3
        toc-expand: true
        code-fold: show
        code-overflow: wrap
        code-tools: 
            source: repo
            toggle: true

execute: 
  warning: false
  error: false